### ISSUE TITLE
Building Model Comparison - IEEE

### ISSUE THREAD

**Issue by ProfessorAkram** [cs-utulsa/VRSandbox#14]
# Overview
Paper regarding 3d scanning methods for developing accurate and usable 3d models.

**Comment by Ku-Bri** [comment]
# PROGRESS

### Research into IEEE Conference Submissions:
Looking at IEEE journal database and google scholar for articles similar to our research to see what angle might best suite our submission. Search terms Digital Twin Model/Modeling/Creation, Digital Twin BIM, Scan to BIM, 

After looking through some submissions to previous IEEE DTPI conferences, I thought the practical application of my research might be more in line with a presentation at the Blender Conference. Blender has playlists for their conferences on their YouTube channel, find last years here:

* https://www.youtube.com/playlist?list=PLa1F2ddGya\_\_2Ip2UB-xp6M54cQVvw1W-

I created a Milestone in GitHub for the Blender Conference 2023 and looked into previous submissions for this conference in order to gauge whether I could present with the experience I have on this project. I have determined that at this point in the project I do not believe I have sufficient novel information to provide meaningful content for a presentation. However, I believe as we progress on this project I will gain enough experience to submit for a presentation at the 2024 conference. 

I do not have access to full IEEE papers/articles without a (paid) subscription to IEEE Xplore database but upon further exploration discovered the university has access to it via this link:

* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/Xplore/home.jsp

Links to useful articles for our submission:
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/10097415

Links to useful articles in general:
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9826964
* https://www.mdpi.com/1424-8220/23/5/2497
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9643761
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9643681
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9540116
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/10115665

Links to articles looked at but not listed above:
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9540131
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9921707
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9247749
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9540122
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9910286
* https://ieeexplore-ieee-org.utulsa.idm.oclc.org/document/9715301

# SLOWDOWNS
My current research has uncovered addition potentially feasible automated/partially automated processes that may speed up model/BIM creation. Exploring these options and the different processes, software, and add-ons is time consuming as it is unclear from the research whether these processes would work or increase the efficiency of our process. 

# COMPLETED

# PROGRESS IMAGES

**Comment by Ku-Bri** [comment]
IEEE DTPI Paper Submitted by Professor Akram 07/30/2023.
